language: erlang
otp_release:
  - 17.0
before_install:
 - sudo apt-get update
 - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
 - sudo apt-get install postgresql-client-common postgresql-9.4
 - sudo service postgresql startnotifications:
recipients:
  - adam@apathydrive.com
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - cp config/config.exs.example config/config.exs
  - cp config/test.exs.example config/test.exs
  - MIX_ENV=test mix do deps.get, compile
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix ecto.migrate ApathyDrive.Repo
script:
  - mix test
env:
  - MIX_ENV=test
