language: erlang
otp_release:
  - 17.0
notifications:
  recipients:
    - adam@apathydrive.com
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir 
  - git reset 9cff61493e9e3626e8d243dfe8aec07230a7fe73 --hard
  - make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
env:
  - MIX_ENV=test
