language: erlang
otp_release:
  - 17.0
notifications:
  recipients:
    - adam@apathydrive.com
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v0.14.2/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - cp lib/apathy_drive/config/config.ex.example lib/apathy_drive/config/config.ex
  - cp lib/apathy_drive/config/test.ex.example lib/apathy_drive/config/test.ex
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
env:
  - MIX_ENV=test
