language: erlang
otp_release:
  - 17.0
addons:
  postgresql: "9.4"
notifications:
  recipients:
    - adam@apathydrive.com
before_install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip
  - unzip -d elixir Precompiled.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - cp config/config.exs.example config/config.exs
  - cp config/test.exs.example config/test.exs
  - MIX_ENV=test mix do deps.get, compile
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - mix test
env:
  - MIX_ENV=test
